#!/bin/bash

sleep 2
echo "Press Reset, release in a few seconds when programming starts..."
sleep 1
echo "4"
sleep 1
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1

~/.platformio/packages/tool-openocd/bin/openocd \
	-s ~/.platformio/packages/tool-openocd \
	-f scripts/interface/stlink.cfg \
	-c 'transport select hla_swd' \
	-f scripts/target/stm32f1x.cfg \
	-c "reset_config none" \
	-c "program generic_boot20_pc13.bin 0x08000000 verify reset; shutdown;"
